### ISSUE TITLE
What are the different 'Items Display Types'

### ISSUE THREAD

**Issue by daene17** [EtchUK/Etch.OrchardCore.Search#15]
![image](https://user-images.githubusercontent.com/8889105/91892858-33423980-ec48-11ea-89a3-d4029c694894.png)

Hi! I want to display just a title and one single content field in my results. How can I do this? I see in this dropdown you can have different options such as Summary and Detail. But I do not know any other display type besides these two and there is nothing in the documentation to give me additional information. Please consider putting a dropdown list for this field.

**Comment by peterkeating** [comment]
Supported display types are kind of dictated by the templates defined in the theme. By the sounds of what you're trying to do you want "Summary" which means you need to define templates for your content types that support display a summary. If you have a content type of "Post", in the theme a template file named `Content-News.Summary.liquid` can define how to display a post as a summary. Worth noting, if you don't define a summary template for a content type, it'll default to using [this template from within Orchard Core](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Views/Content.Summary.cshtml).

The reason we won't be changing the display type to a drop down list is because the display type could be anything, it's up to the theme developer to support the display types that are defined within the CMS.

You can read more about display types on the Orchard Core docs - https://docs.orchardcore.net/en/dev/docs/reference/modules/Themes/#display-types
