### ISSUE TITLE
How we can use this module in Decoupled approch of orchard cms

### ISSUE THREAD

**Issue by MuhammadTalha10** [EtchUK/Etch.OrchardCore.Search#6]
Hi, I am creating a website using orchard CMS and I adopted decoupled approach I want to know how to use site search content item in this scenario (decoupled)

**Comment by peterkeating** [comment]
@MuhammadTalha10 Can't say I've implemented a decoupled approach before. This module was created due to features that were missing or difficult to implement with out the box Orchard Core. However, what's needed to achieve site search should be possible without the need of this module so I'd suggest trying to use the default search features to achieve your site search.
